---
title: "About me"
output:
  distill::distill_article:
    toc: false
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(fontawesome)
```


Hi there! `r emo::ji("wave")`

My name is Malte, I am junior researcher both living and working
in Berlin/Germany.
I am coming from the political science field, which I studied at the University 
of Konstanz -- however, I shifted a bit towards statistics and computer science.
Currently, my work includes small area estimation,
(spatial) data integration, and the like. I enjoy learning more on how
to implement the notion of reproducible, robust research infrastructure.
In particular, I am eager to dive deeper into database engineering and the design
of data systems.

A friend of mine (who has a [nice blog](https://frie.codes) running) has _repeatedly_ and _restlessly_
encouraged me to get started with blogging about technical topics, so I finally
will give it a try `r emo::ji("grimace")`. Thus, I hope that over time some
interesting posts will come into existence to justify the  presence of this
website!

## Reading list

In my spare time, I am currently trying to read some bits of the following
books (with scientific/technical content), and I'd be open about any form
of exchange:

* Gottschling, Peter. 2019. _Forschung mit modernem C++_
* Hodges, James S. 2013. _Richly Parameterized Linear Models_
* Kleppmann, Martin. 2017. _Designing Data-intensive Applications_
* McElreath, Richard. 2020. _Statistical Rethinking_
* Noback, Matthias. 2020. _Object Design Style Guide_
* Rao, J.N.K. and Isabel Molina. 2015. _Small Area Estimation_
